### PR TITLE
2.5.5 release

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by dpryan79** [comment]
Gah, forgot that, thanks!

**Comment by bgruening** [comment]
Are we sure it does not break any tests :)

**Comment by dpryan79** [comment]
Meh, the Galaxy tests are already broken in master (fixed in develop), due to some dependency thing with Galaxy.

**Comment by bgruening** [comment]
Ok, I will test this locally and upload if successful. I guess you don't want to me fix master?

**Comment by dpryan79** [comment]
Nah, don’t bother.

**Pull request merged**
