### PR TITLE
fixes linting issues

### PR DESCRIPTION
**Pull request by bgruening**
@dpryan79 does this look ok for you?

Upload did not work due to a linting issue.

### CODE REVIEW

**Comment by dpryan79** [comment]
Yes! I wonder why the CI tests didn't fail...

**Comment by bgruening** [comment]
Planemo lint fails, but does not return an error code in this case :(

**Comment by dpryan79** [comment]
That's unfortunate :(

**Comment by bgruening** [comment]
If you merge this one. I will proceed with upload. Thanks!

**Comment by dpryan79** [comment]
Done, thanks!

**Pull request merged**
