### PR TITLE
Fix 1013

### PR DESCRIPTION
**Pull request by LeilyR**
inspired by #1013

### CODE REVIEW

**Comment by LeilyR** [comment]
Hi @dpryan79,  sorry to bother you. Could you please have a look at [this](https://github.com/deeptools/deepTools/pull/1018/checks?check_run_id=1478936777#step:3:138). I think it needs to be fixed under account. Let me know if there anything I can do for it. Thanks a lot!

**Comment by dpryan79** [comment]
@LeilyR I'll see what I can do

**Comment by LeilyR** [comment]
@dpryan79 Thanks a lot

**Comment by LeilyR** [comment]
Just to let you know, this pc2 value changes frequently between those two numbers, sometime is 1.2325951644078315e-32 some other time is 2.49319462166397e-32. I have seen both of them.

**Comment by dpryan79** [comment]
Yeah, I think it depends on the CPU that gets used.

**Comment by dpryan79** [comment]
@LeilyR can you check computeMatrixOperations locally? It's running rbind and I have no clue why it's immediately throwing an error.

**Comment by LeilyR** [comment]
@dpryan79  I have already tried it locally and it fails there too. I was also really confused, since it says it cannot find the `info` command. with the updated galaxy version also master branch fails for this test, Though I could  get to run the 3.4.3 version locally with no issue. 3.4.3 is the latest version before introducing `dataRange`. What I do not understand is that if that is the problem why rbind test passes. Also `info` used to pass before we change the  galaxy version.  I will have a look at it again, but if you also have any opinion I would be happy to hear. Again thank a million for looking into it.

**Comment by dpryan79** [comment]
I mean on the command line, does it run properly there with `computeMatrixOperations rbind ...`? The data is under galaxy/wrapper/test-data.

**Comment by LeilyR** [comment]
I see ok thanks , i will check

**Comment by LeilyR** [comment]
Hi @dpryan79 , I got to fix the galaxy issues. However there is an issue with the tests running under your account. The error is: 
` Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/`
Could you please update this? Do you think I should merge my PR despite those failures?

**Comment by dpryan79** [comment]
The azure tests are all green so it's safe to merge. I'll see if I can get the environment variable set properly. Otherwise I'll just update the nodejs stuff, which should get migrated to the deeptools repo so others can update it more easily.

**Comment by dpryan79** [comment]
It only fails on the annoying plotPCA test. Long-term we might just remove that, since it results only in false positive errors.

**Comment by LeilyR** [comment]
thanks a lot @dpryan79 ! I will merge it then :)

**Pull request merged**
