### PR TITLE
changed auto to best

### PR DESCRIPTION
**Pull request by LeilyR**
**Welcome to deepTools GitHub repository! Please check the following regarding
your pull request :**

 - [ ] Does the PR contain new feature?
 - [x ] Does the PR contain bugfix? #1041 , #1042 
 - [ ] Does the PR contain documentation changes?
 - [ ] Does the PR contain changes to the galaxy wrapper?

### CODE REVIEW

**Comment by dpryan79** [comment]
The galaxy tests are expected to fail then, since some of them will compare the images. Can you see if you can determine when matplotlib added "best" so we can update the matplotlib version restriction?

**Comment by LeilyR** [comment]
sure, i will have a look

**Comment by LeilyR** [comment]
the best option seems to be already availble since version2, this was taken care of for the cli , the default was already set to best, but in the init was auto which i suppose will through an error only if one uses the api.  Planemo test seems to be failed at deeptools_bam_pe_fragmentsize where comparing some tables, some little differences between values (241.20000000000002 instead of 241.2). I thought it could be related to the server the tests are run on it, so I tried to re-run the tests but it did not help. If you do not mind I ginore the error for now and merge this little bug fix to develop desipte the error and we see if it comes up we merging to master again and fix it then.
In general I wonder if we should remove this type of tests from planemo, since it really seems that it is not capable of handelign them. Do you have any idea for that?

**Comment by dpryan79** [comment]
It's a double-edged sword. The benefit to keeping them in is we catch more subtle issues with plotting. So I would vote to keep them in, but wouldn't be terribly disappointed if you said, "Gah! I've had enough of these false-positive failures. Let's remove them!" :)

**Comment by dpryan79** [comment]
Sure, :+1: on merging from my side :)

**Pull request merged**
