### PR TITLE
update versions of tool wrappers

### PR DESCRIPTION
**Pull request by lldelisle**
**Welcome to deepTools GitHub repository! Please check the following regarding
your pull request :**

 - [ ] Does the PR contain new feature?
 - [ ] Does the PR contain bugfix?
 - [ ] Does the PR contain documentation changes?
 - [X] Does the PR contain changes to the galaxy wrapper?

Adopt the version style of tools-iuc: deeptools version +galaxyN

Update deeptools version from 3.5.1 to 3.5.2

### CODE REVIEW

**Comment by lldelisle** [comment]
@bgruening would you mind to merge this and deploy to toolshed?
There is a tool on toolshed which cannot work: https://toolshed.g2.bx.psu.edu/view/bgruening/deeptools_bigwig_average/9987ddd67710 (I was not expecting that the version of deeptools was changed without the macro of galaxy wrappers). Can we mark it as 'unusable'?

**Review by bgruening — COMMENTED** [review]
Can you please macro'fy the profile version and bump it to some more recent version please?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Mh, we should always change it in the macro isn't it. Exception is the +galaxy version, that can be changed per tool if really needed. I will see if I can deprecate the tool once I have net

**Comment by lldelisle** [comment]
Thanks. Please, let me know when you put them on toolshed.

**Pull request merged**
