### PR TITLE
changed itmesiter() in estimateEscaleFactor to its python3 compatible items()

### PR DESCRIPTION
**Pull request by LeilyR**
changed itmesiter() in estimateEscaleFactor to its python3 compatible items(). This PR addresses #942 issue.

**Welcome to deepTools GitHub repository! Please check the following regarding
your pull request :**

 - [ ] Does the PR contain new feature?
 - [x] Does the PR contain bugfix?
 - [ ] Does the PR contain documentation changes?
 - [ ] Does the PR contain changes to the galaxy wrapper?

### CODE REVIEW

**Comment by dpryan79** [comment]
Can you grep through the code and see if iteritems() slipped in anywhere else? Thanks for fixing this :)

**Comment by LeilyR** [comment]
that seemed to be the only one

**Comment by dpryan79** [comment]
Great, do you want to bump the build number and then tag a new release once this is merged in or should I? Tagging a release automatically uploads a tarball to pypi, so you don't have to do any of that :)

**Comment by LeilyR** [comment]
sure, since I have it open here on my machine I can quickly take care of the version number too.  change the third digit only, right?

**Comment by dpryan79** [comment]
Yes, please also change the version in the Galaxy wrapper and update the release notes to mention that this was fixed.

**Comment by dpryan79** [comment]
BTW, you can ignore the last failure, that happens sometimes.

**Comment by dpryan79** [comment]
Thanks!

**Comment by LeilyR** [comment]
sure thing!

**Pull request merged**
