### PR TITLE
increase matloblib version

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@dpryan79 starting the upload. Conda should be fixed, more infos via mail.

**Comment by dpryan79** [comment]
Yup, conda is happy now. I'll merge once travis is happy. I'll also update the conda recipe (unless you're already doing that).

**Comment by dpryan79** [comment]
Actually, there are a couple of places that the requirements are listed, I'll just update them all directly.

**Comment by dpryan79** [comment]
See the `hotfix/requirements_fix` branch. Once that passes testing I'll merge to master and develop (I do enjoy git flow).

**Pull request closed without merging**
