### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by vivekbhr**
1. added issues, contributing and PR templates (@dpryan79 have a look)
2. Testing if coveralls works (if not I would remove that)

### CODE REVIEW

**Comment by dpryan79** [comment]
Templates look good, thanks! I'm not sure how useful coveralls will be, the percentage will always be small unless out CI tests take a couple hours.

**Comment by vivekbhr** [comment]
Coveralls needs the test report output from coverage, pytest-cov, or nosexcover , but I think we are not using any of them for our tests, so it won't be useful

**Comment by vivekbhr** [comment]
======================================================================
FAIL: bigwigCompare ( deeptools_bigwig_compare ) > Test-2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmpTSRg9Y/galaxy-dev/test/functional/test_toolbox.py", line 317, in test_tool
    self.do_it(td)
  File "/tmp/tmpTSRg9Y/galaxy-dev/test/functional/test_toolbox.py", line 83, in do_it
    raise e
JobOutputsError: No JSON object could be decoded

:sob:

**Comment by dpryan79** [comment]
Galaxy tests fail on occasion for a variety of unrelated reasons. I split them into 3 chunks so they'd be quicker to rerun :)

**Pull request merged**
